### ISSUE TITLE
Need clarification about backed page

### ISSUE THREAD

**Issue by waseemanwar1** [dezman/beatoftheday#45]
As an user when I logged into the Baked page I can add new tracks.
after successful upload it is showing into my artist page, path: `root/artist/username`.
but uploaded tracks are not showing into `root/backed` page.

**Comment by dezman** [comment]
@waseemanwar1 The baked page is like "top" on reddit. There is an algorithm on the back end to define what "baked" means. It is a combination of the number of "bakes" the track has received from other users, and how recent the track was uploaded.
